### ISSUE TITLE
只要引入这个Bar就crash。暂未找到解决方法

### ISSUE THREAD

**Issue by zhangyc** [xiaohaibin/CustomTitleBar#6]
FATAL EXCEPTION: main
                                                   Process: com.taikang.weneed.app.mine, PID: 16865
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.taikang.weneed.app.mine/com.taikang.weneed.app.mine.activity.LoginActivity}: android.view.InflateException: Binary XML file line #11: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f01004a a=-1}
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2717)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2778)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1511)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6244)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)
                                                    Caused by: android.view.InflateException: Binary XML file line #11: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f01004a a=-1}
                                                    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f01004a a=-1}
                                                       at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:761)
                                                       at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:7040)
                                                       at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7221)
                                                       at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1926)
                                                       at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1824)
                                                       at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1823)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:860)
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                       at com.taikang.weneed.app.mine.activity.LoginActivity.onCreate(LoginActivity.java:40)
                                                       at android.app.Activity.performCreate(Activity.java:6731)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2670)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2778)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1511)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6244)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)

**Comment by limuyang2** [comment]
未出现你说的情况
